
CREATE TABLE theLoai
(
	idTL INT PRIMARY KEY NOT NULL,
	TenTL NVARCHAR(100) NOT NULL,
	anHien_TL TINYINT NULL
)

CREATE TABLE loaiTin
(
	idLT INT PRIMARY KEY NOT NULL,
	Ten NVARCHAR(100) NOT NULL,
	Url VARCHAR(255) NULL,
	anHien_LT tinyint NOT NULL,
	Target NVARCHAR(10) NULL,
	IconHinh VARCHAR(255) NULL,
	idTL INT FOREIGN KEY (idTL) REFERENCES theLoai(idTL) NOT NULL
)

CREATE TABLE Tin
(
	idTin INT PRIMARY KEY NOT NULL,
	TieuDe NVARCHAR(255) NOT NULL,
	TomTat NVARCHAR(1000) NULL,
	urlHinh VARCHAR(255) NULL,
	Ngay DATE NULL,
	idUser INT NOT NULL,
	idSK INT NULL,
	TrangThai INT NULL, 
	idTL INT FOREIGN KEY (idTL) REFERENCES theLoai(idTL) NULL,
	idLT INT FOREIGN KEY (idLT) REFERENCES loaiTin(idLT) NOT NULL
)

CREATE TABLE suKien
(
	idSK INT PRIMARY KEY NOT NULL,
	MoTa NVARCHAR(255) NOT NULL
)

CREATE TABLE User
(
	idUser INT PRIMARY KEY NOT NULL,
	HoTen NVARCHAR(100) NOT NULL,
	UserName NVARCHAR(50) NOT NULL,
	PassWord NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(255) NULL,
	DienThoai NVARCHAR(255) NULL,
	Email NVARCHAR(255) NOT NULL,
	NgayDangKy DATE NOT NULL,
	Group NVARCHAR(50)
)